### ISSUE TITLE
Exception from SourceIndexServer.Models.Query.StripQuotes

### ISSUE THREAD

**Issue by npip99** [KirillOsenkov/SourceBrowser#100]
https://referencesource.microsoft.com/#q=gggg%5Cgggg%22

The URL above seems to throw an error that comes from this repo, when searching for `gggg\gggg"`

> System.ArgumentOutOfRangeException: Length cannot be less than zero. Parameter name: length at System.String.Substring(Int32 startIndex, Int32 length) at SourceIndexServer.Models.Query.StripQuotes(String text, Boolean& isQuoted) at SourceIndexServer.Models.Index.FindAssemblies(Query query, Boolean defaultToAll) at SourceIndexServer.Models.Index.Get(String queryString) at SourceIndexServer.Controllers.SymbolsController.GetHtmlCore(String symbol, String usageStats) at SourceIndexServer.Controllers.SymbolsController.GetHtml(String symbol)

**Comment by KirillOsenkov** [comment]
Thanks!
