### ISSUE TITLE
Memory leak / crash when generating for large number of projects

### ISSUE THREAD

**Issue by yaakov-h** [KirillOsenkov/SourceBrowser#109]
Using 1.0.20 from NuGet.

After a while HtmlGenerator.exe logs and crashes with an OutOfMemoryException.

Memory usage just keeps climbing and climbing over time:

![image](https://user-images.githubusercontent.com/426009/50750501-3c271000-1299-11e9-9e06-e9aba301192c.png)

Based on some quick profiling it seems like the static field `mergedSolutionExplorerRoot` is holding on to each `Project` which internally holds on to each `Solution` and `CSharpCompilation`, and basically tries to keep in-memory the entire contents of all of my projects until it eventually dies.

**Comment by KirillOsenkov** [comment]
As a temporary workaround, can you try to switch to 64-bit and see if the crash at least goes away?

https://github.com/KirillOsenkov/SourceBrowser/blob/8ee54b1d971b9fea73ff124ac1622e02c068fb8a/src/HtmlGenerator/HtmlGenerator.csproj#L9

**Comment by reegeek** [comment]
hi @KirillOsenkov, do you fix the memory leak ?

**Comment by reegeek** [comment]
this pull request improve the memory consumption. #120
