### ISSUE TITLE
Escape sequences in strings displayed incorrectly

### ISSUE THREAD

**Issue by svick** [KirillOsenkov/SourceBrowser#125]
When a string contains an escape sequence, SourceBrowser displays it twice. For example, the code:

```c#
public static string NewLine => "\r\n";
```

[Is displayed as:](https://source.dot.net/#System.Private.CoreLib/shared/System/Environment.Windows.cs,50)

![image](https://user-images.githubusercontent.com/287848/64479477-dc7e5d00-d1b7-11e9-8c91-ed9b764760fd.png)

**Comment by KirillOsenkov** [comment]
Here's the code that generates it:
https://github.com/KirillOsenkov/SourceBrowser/blob/d8b1d1b04003312ca187290a7ac941dc123e0658/src/HtmlGenerator/Pass1-Generation/DocumentGenerator.cs#L419
