### ISSUE TITLE
Host "https://source.dot.net" locally in IIS to browse .NET Core code

### ISSUE THREAD

**Issue by Legends** [KirillOsenkov/SourceBrowser#127]
Is it possible and how can it be accomplished, explained shortly?

Because oftenly I get this when using the online version of `source.dot.net`:

![image](https://user-images.githubusercontent.com/966368/66202144-41d54900-e6a5-11e9-80b8-f08a831f7026.png)
<hr>

When I try to execute `Build.cmd` I get:
```
msbuild /r /m /bl
Microsoft (R) Build Engine version 14.0.25420.1
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1001: Unknown switch.
Switch: /r

For switch syntax, type "MSBuild /help"
```

**Comment by KirillOsenkov** [comment]
Your MSBuild is too old (14). Install Visual Studio 2019 (16.3) and try again.

Not sure why the official website doesn’t work. Check your network or try a different browser or machine.

It will be difficult to index CoreFX locally.

**Comment by Legends** [comment]
It works with Edge but not with latest Chrome :D usually it's the other way around..
Yeah, I was using the wrong dev console.
