### ISSUE TITLE
Question: https://source.dot.net/

### ISSUE THREAD

**Issue by Legends** [KirillOsenkov/SourceBrowser#128]
To which version of .net core does the source browser point to?
Is it master or a certain version?

Sorry, I know it's not directly related to SourceBrowser.

**Comment by WeihanLi** [comment]
it seemed was <https://github.com/dotnet/corefx/tree/8245ee1e8f6063ccc7a3a60cafe821d29e85b02f>

you can found the github source on the bottom right in the details code page

![image](https://user-images.githubusercontent.com/7604648/67632282-77540780-f8dc-11e9-9048-c7f9296b318d.png)

**Comment by Legends** [comment]
Ah yes, thanks!
