### ISSUE TITLE
SourceBrowser started failing lately

### ISSUE THREAD

**Issue by mvestergaard** [KirillOsenkov/SourceBrowser#129]
Hi,

Lately (since friday I think). SourceBrowser is failing during our nightly CI process with this message:
`The remote name could not be resolved: 'source.roslyn.io'`

Any chance this can be resolved?

**Comment by KirillOsenkov** [comment]
Ah yes, I will need to change it to http://sourceroslyn.io (without the dot).

**Comment by KirillOsenkov** [comment]
Fixed and published https://www.nuget.org/packages/SourceBrowser/1.0.25

**Comment by mvestergaard** [comment]
Cool, thanks Kirill!

**Comment by vadimart92** [comment]
Hi,
maybe you should also include https://source.dot.net/  ?

**Comment by KirillOsenkov** [comment]
That's difficult because it has the source for .NET Core, not .NET Framework. I wouldn't want to mix desktop and core, there are lots of issues there. One would want to use that instead of referencesource.microsoft.com for indexing .NET Core repos.
