### ISSUE TITLE
System.Net.WebException

### ISSUE THREAD

**Issue by levi930** [KirillOsenkov/SourceBrowser#136]
var assemblyList = new WebClient().DownloadString(url); 
yet must be set ServicePointManager.SecurityProtocol = SecurityProtocolType.Ssl3| SecurityProtocolType.Tls | SecurityProtocolType.Tls11|   SecurityProtocolType.Tls12;

**Comment by KirillOsenkov** [comment]
Thanks for reporting an issue. I don't know much about this. Are you suggesting I should add that line before or after the DownloadString call? Care to submit a PR?

**Comment by levi930** [comment]
before,you set only once; add that line before ;
like this
    static Federation()
        {
            ServicePointManager.SecurityProtocol = SecurityProtocolType.Ssl3 | SecurityProtocolType.Tls | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12;

        }

**Comment by KirillOsenkov** [comment]
https://github.com/KirillOsenkov/SourceBrowser/commit/6f67c30dfc45c2a21a3d53cc250a844b4349d58d

**Comment by vcsjones** [comment]
@levi930 why do you need this? In general, setting the `SecurityProtocol` explicitly is not recommended. This stops the underlying platform from using its preferred SSL/TLS version. For example, this is re-enabling SSLv3 where a platform prefers it is disabled, and is opting out of TLSv1.3 when the platform gets support for it.

Refer to https://docs.microsoft.com/en-us/dotnet/framework/network-programming/tls#for-http-networking for further detail.

**Comment by KirillOsenkov** [comment]
Unfortunately due to the very limited description of the issue and no explanation I'm going to roll this change back.

The community is generally advising against using ServicePointManager. Please let us know if you have a more detailed explanation for us.

**Comment by KirillOsenkov** [comment]
https://github.com/KirillOsenkov/SourceBrowser/commit/cea2976a3917f3cb492803dcd3289f7add14e866

**Comment by levi930** [comment]
> @levi930 why do you need this? In general, setting the `SecurityProtocol` explicitly is not recommended. This stops the underlying platform from using its preferred SSL/TLS version. For example, this is re-enabling SSLv3 where a platform prefers it is disabled (because is it not secure), and is opting out of TLSv1.3 when the platform gets support for it.
> 
> Refer to https://docs.microsoft.com/en-us/dotnet/framework/network-programming/tls#for-http-networking for further detail.

sorry,I am not goot at english, In this case,if your not set    ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12 | SecurityProtocolType.Tls11; you will get error when use 
new WebClient().DownloadString(url);  specify SSL protocol to use for WebClient class,visist https

**Comment by levi930** [comment]
> Unfortunately due to the very limited description of the issue and no explanation I'm going to roll this change back.
> 
> The community is generally advising against using ServicePointManager. Please let us know if you have a more detailed explanation for us.
I am sorry,I am not good at english.visist https use WebClient().DownloadString(url),must 
specify SSL protocol to use for WebClient class.

**Comment by levi930** [comment]
use  WebClient().DownloadString(url)  visit https://referencesource.microsoft.com,
I meaning you must specify SSL protocol
