### ISSUE TITLE
https://source.dot.net outage - index is missing types

### ISSUE THREAD

**Issue by StipoR** [KirillOsenkov/SourceBrowser#137]
Few days ago I was able to view [SignedCms](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.pkcs.signedcms) class and other related classes in [System.Security.Cryptography.Pkcs](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.pkcs) namespace through [.NET Core Source Browser](https://source.dot.net/#q=SignedCms), but now I cannot find any class from System.Security.Cryptography.Pkcs namespace in .NET Core Source Browser anymore.

Using .NET Core Source Browser it was easy for me to find all references to some member and generally move through code with a need to download anything.

[.NET Framework Reference Source](https://referencesource.microsoft.com/#System.Security/system/security/cryptography/pkcs/signedpkcs7.cs,450a89c7062d7944) still contains SignedCms class, but that implementation is not cross-platform and doesn't interest me.

Doesn't anyone know why this is happening?

Is this maybe because [.NET Core FX](https://github.com/dotnet/corefx) repository was moved to [.NET Runtime](https://github.com/dotnet/runtime) repository?

**Comment by KirillOsenkov** [comment]
@alexperovich maybe knows? anything new in errors.txt?

**Comment by alexperovich** [comment]
this is this issue https://github.com/dotnet/core-eng/issues/9537

The runtime repo recently updated versions and its causing problems. We are getting this from every project in runtime despite installing the version of .net specified in global.json.
```
Msbuild failed when processing the file 'F:\workspace\_work\1\s\bin\repo\runtime\src\coreclr\src\System.Private.CoreLib\System.Private.CoreLib.csproj' with message: The SDK 'Microsoft.NET.Sdk' specified could not be found.
```

**Comment by StipoR** [comment]
@alexperovich Thanks for investigating this issue.

The link you provided is broken.
Could you please provide the correct link and I will continue with this in that repository?

**Comment by KirillOsenkov** [comment]
@StipoR that's a private repo with some internal engineering tools. We'll reply here when this is resolved.

Thanks again for reporting!

**Comment by NetMage** [comment]
Is this the same reason List<T> can't be found?

**Comment by KirillOsenkov** [comment]
Yes, all kinds of brokenness right now, and we're investigating.

**Comment by IrisClasson** [comment]
Saw the comment here. Seems like the issue I submitted is related.

**Comment by KirillOsenkov** [comment]
We've made some progress: https://twitter.com/KirillOsenkov/status/1251312839353970688
We'll try out the new approach next week and see if it works.

**Comment by KirillOsenkov** [comment]
This is now fixed. Thanks to @alexperovich. 

There's one remaining minor issue that the type forwarding is not respected, but we'll deal with it soonish.
