### ISSUE TITLE
Unable to locate dotnet/aspnetcore project in source.dot.net

### ISSUE THREAD

**Issue by jasonkuo41** [KirillOsenkov/SourceBrowser#141]
Prior to the .Net 5 index fix, I was able to navigate projects that are from dotnet/aspnetcore, for example, Microsoft.AspNetCore, Microsoft.AspNetCore.WebHost etc..

After the fix, these projects are nowhere to be found on source.dot.net, would be grateful if you can include them again, thank you.

**Comment by KirillOsenkov** [comment]
@alexperovich

**Comment by alexperovich** [comment]
This is not working because the aspnetcore build for the indexer isn't working. I will fix it.

**Comment by alexperovich** [comment]
I have fixed this.

**Comment by KirillOsenkov** [comment]
Awesome job Alex.
