### ISSUE TITLE
Unable to find source code for key methods

### ISSUE THREAD

**Issue by kunalspathak** [KirillOsenkov/SourceBrowser#149]
I am not able to find code for many methods present in `System.Runtime`, `System.Common`, etc.. E.g. `ProcessArchitecture`. Is anything broken?

**Comment by kunalspathak** [comment]
Even https://source.dot.net/#q=BitConverter doesn't return any result.

**Comment by KirillOsenkov** [comment]
This is known and tracked here: https://github.com/dotnet/source-indexer/issues/60

**Comment by kirsan31** [comment]
https://github.com/dotnet/source-indexer/issues/60 is closed now but most things is not working (`JsonSerializer`, `System.Windows.Forms`...) :(

**Comment by alexperovich** [comment]
The wpf build broke, so its not indexing due to that. The winforms build appears to be correct, but for some reason the System.Windows.Forms assembly isn't getting indexed.

**Comment by kirsan31** [comment]
@alexperovich
JsonSerializer is some how working now. And about WinForms I have opened [issue](https://github.com/dotnet/source-indexer/issues/70) about week ago...

**Comment by alexperovich** [comment]
Yea, there was an azure devops outage that caused some hiccups over the weekend. I don't have a lot of cycles available to diagnose the winforms issue, but I will investigate it when I can.
