### ISSUE TITLE
System.IO.FileSystem.Win32.cs missing from source.dot.net

### ISSUE THREAD

**Issue by NetMage** [KirillOsenkov/SourceBrowser#150]
When attempting to view the source for File.Encrypt, it shows a call to FileSystem.Encrypt which is in FileSystem.Unix.cs which just throws an unimplemented Exception.

Wouldn't it be better to show FileSystem.Win32.cs where the method is actually implemented?

**Comment by KirillOsenkov** [comment]
When there are two projects with the same assembly name, only the first one gets indexed, this is a fundamental limitation of SourceBrowser. Unfortunately it so happens that the assembly where this method is not implemented gets indexed first, and wins.

Maybe if we manually exclude this one, the other one will start taking precedence? I'm not sure if this is the actual problem, just guessing here.

@alexperovich any thoughts on this? Is this a situation where the less preferable version of an assembly is being indexed first?

**Comment by alexperovich** [comment]
We have intentionally made source.dot.net index the linux sources at the request of the runtime team.

**Comment by KirillOsenkov** [comment]
OK, then I'm closing this as there isn't much we can do to fix this due to the SourceBrowser design limitation.
