### ISSUE TITLE
Internal classes are not resolved correctly

### ISSUE THREAD

**Issue by andre-ss6** [KirillOsenkov/SourceBrowser#151]
Example: https://source.dot.net/#System.Private.CoreLib/CancellationTokenRegistration.cs,78

See how on the `CancellationTokenSource.CallbackNode` declaration, CallbackNode is not colored and is not clickable, nor is its references and method calls.

My team and I are using ReferenceSource to try to solve a memory leak we're having related to Kestrel. Is there any workaround to this?

**Comment by KirillOsenkov** [comment]
This is because we need to update SourceBrowser to the latest Roslyn version.
https://source.dot.net/System.Private.CoreLib/Diagnostics.txt

**Comment by KirillOsenkov** [comment]
@alexperovich wanna pull my latest master? I bumped to 3.8.0-beta3.final and added dark theme.

**Comment by alexperovich** [comment]
Yep, i'll update source.dot.net with the latest.

**Comment by andre-ss6** [comment]
It seems to be working now! Thanks a lot!
