### ISSUE TITLE
Please index the azure-activedirectory-identitymodel-extensions-for-dotnet repositories

### ISSUE THREAD

**Issue by JoeMarkov** [KirillOsenkov/SourceBrowser#154]
I wish that I could search and browse the source code for the identity and OpenIDConnect code found here:

https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet

For example right now I can't find classes like OpenIdConnectConfiguration and ConfigurationManager that is referenced by some of the authentication handlers.

that classes are found here:
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/master/src/Microsoft.IdentityModel.Protocols.OpenIdConnect/Configuration/OpenIdConnectConfiguration.cs

https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/master/src/Microsoft.IdentityModel.Protocols/Configuration/ConfigurationManager.cs

It is very useful to be able to browse these libraries when you are researching and working the the authentication and authorization in .NET

**Comment by KirillOsenkov** [comment]
Unfortunately this was not designed to scale arbitrarily so we're not open to adding new repos at this point. Sorry about that!
We're not funded to scale and doing this mostly on volunteer basis.
