### ISSUE TITLE
C#9 Function Pointers do not count as reference

### ISSUE THREAD

**Issue by fbrosseau** [KirillOsenkov/SourceBrowser#155]
Hello

Thanks for the project, it is very useful!

It looks like the new C#9 Function Pointers feature do not count as a reference to the method they point to.

For example, looking here:
https://source.dot.net/#System.Net.Security/Interop.OpenSsl.cs,438
It claims there are no references to method `VerifyClientCertificate`. Furthermore, on the line that actually does reference this method, (through the new "get function pointer" syntax) `SslCtxSetVerify` is not clickable either, and the browser also thinks that there are no usages of `SslCtxSetVerify`.

**Comment by KirillOsenkov** [comment]
We just need to update to the latest Roslyn.

**Comment by KirillOsenkov** [comment]
I've updated to Roslyn 3.9. @alexperovich whenever you have a moment, mind merging my master?

**Comment by fbrosseau** [comment]
This appears to be fixed on source.dot.net now. Thanks!
