### ISSUE TITLE
source.dot.net cannot search out ServiceCollectionServiceExtensions

### ISSUE THREAD

**Issue by lateapexearlyspeed** [KirillOsenkov/SourceBrowser#156]
Hi,
https://source.dot.net/ is a very powerful website to search and learn net core code.
I remember I can search out ServiceCollectionServiceExtensions from https://source.dot.net/ at least half year ago but now seems cannot any more.
The code in git is [here](https://github.com/dotnet/runtime/blob/master/src/libraries/Microsoft.Extensions.DependencyInjection.Abstractions/src/ServiceCollectionServiceExtensions.cs)

I am not sure if issue should be raised here but just try to ask, thanks for help !

**Comment by KirillOsenkov** [comment]
@alexperovich do you know if this is supposed to be indexed:
https://github.com/dotnet/runtime/blob/master/src/libraries/Microsoft.Extensions.DependencyInjection.Abstractions/src/ServiceCollectionServiceExtensions.cs

**Comment by lateapexearlyspeed** [comment]
Hi @KirillOsenkov , I do not know this info. Should I ask dotnet/runtime repo for that?

**Comment by lateapexearlyspeed** [comment]
Thanks, just found 'ServiceCollectionServiceExtensions' can be searched from  [ https://source.dot.net/]( https://source.dot.net/) now, I close it now.

**Comment by alexperovich** [comment]
Yea, it should be indexed. The reason is wasn't is because the runtime build failed before it was able to build it.
