### ISSUE TITLE
Does it support multiple project releases?

### ISSUE THREAD

**Issue by neeraj9** [KirillOsenkov/SourceBrowser#157]
SourceBrowser is amazing and its usage in https://source.dot.net/ is great. I'd like to use this project, but would like to have support for multiple releases / versions. Is it possible to achieve it in some way?

Lets say project A is having multiple releases 1.0.0, 1.1.0, and so on. Is it possible or any workaround to host source browser for these releases? Any pointers will be of great help.

**Comment by KirillOsenkov** [comment]
Nothing other than creating an individual site for each release, sorry. Only one branch/version is supported.

**Comment by neeraj9** [comment]
Can the same server application host multiple versions if generated separately or do we have to run multiple server processes under different folders?

**Comment by KirillOsenkov** [comment]
I’m afraid even folders are not supported. The Url structure expects to be at the root of the domain. You can host each site on a separate subdomain or a different port such as :8080

**Comment by neeraj9** [comment]
Ah! alright.
