### ISSUE TITLE
NativeIntegerTypeDecoder+ErrorTypeException warnings

### ISSUE THREAD

**Issue by jnm2** [KirillOsenkov/SourceBrowser#158]
Every solution I pass to HtmlGenerator.exe in https://www.nuget.org/packages/SourceBrowser/1.0.34 produces hundreds of these warnings:

> First chance exception while processing assembly: SomeAssemblyName
> Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.NativeIntegerTypeDecoder+ErrorTypeException: Exception of type 'Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.NativeIntegerTypeDecoder+ErrorTypeException' was thrown.
>   at Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.NativeIntegerTypeDecoder.TransformType(TypeSymbol type)

Versions of Visual Studio installed: 16.9.3, 16.10.P1

Would it help if I attached a repro project?

What does this warning mean?

**Comment by KirillOsenkov** [comment]
This is probably benign, it's just a first-chance exception deep in the bowels of Roslyn, it's being caught I'm guessing.

I guess I should try bumping Roslyn to latest? But it might not be fixed. Also it might be a real bug in Roslyn that's masked.

**Comment by KirillOsenkov** [comment]
Haha would you look at that:
https://github.com/dotnet/roslyn/issues/49823

**Comment by jnm2** [comment]
The 1.0.33 NuGet package doesn't have this issue, if that helps. I see the only difference is updating Roslyn to 3.9.0-2.final`.

Closing since this is upstream and probably benign. If you wanted to track something, feel free to reopen.
