### ISSUE TITLE
Putting projects within folders in the sidebar

### ISSUE THREAD

**Issue by jnm2** [KirillOsenkov/SourceBrowser#159]
This is the result of passing a long list of .sln paths for all the Git repos at work. Csprojs are intermingled from unrelated software projects in an alphabetical flat list:

![image](https://user-images.githubusercontent.com/8040367/114787958-a7040300-9d4e-11eb-907b-4bb126d415d0.png)

Is there a way I could invoke HtmlGenerator or in some way structure the repos so that csprojs end up within top-level folders of my choosing?

**Comment by KirillOsenkov** [comment]
There isn't much flexibility here unfortunately. 

https://github.com/KirillOsenkov/SourceBrowser/blob/main/src/HtmlGenerator/Pass2-Finalization/SolutionFinalizer.SolutionExplorer.cs

It's all yours ;)

**Comment by jnm2** [comment]
Would you accept a contribution to allow a root directory to be optionally specified? E.g. `/root:"C:\Some\Containing\Dir`? If specified, any sln not contained by that directory would be an error, and the relative folder path from each sln to the root would be visible in the solution explorer.

**Comment by KirillOsenkov** [comment]
sure
