### ISSUE TITLE
What action should I take when projects don't have matching metadata references?

### ISSUE THREAD

**Issue by jnm2** [KirillOsenkov/SourceBrowser#160]
I got this for every solution, so I started running `msbuild /t:Restore` on each one first. Now this is only happening with a couple of solutions.

Does it result in degraded functionality? Where should I start looking to fix it?

```
Generating Some.sln
Workspace failed: Found project reference without a matching metadata reference: Some.csproj
Found project reference without a matching metadata reference: Some.csproj
Workspace failed: Found project reference without a matching metadata reference: Other.csproj
Found project reference without a matching metadata reference: Other.csproj
```

This warning occurs right after the error lines. Could it be related?

> First chance exception
> System.IO.PathTooLongException: Path: C:\Users\jmusser\.nuget\packages\microsoft.netcore.app.ref\5.0.0-rc.2.20475.5\ref\net5.0\C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.runtime.interopservices.runtimeinformation\4.3.0\ref\netstandard1.1\System.Runtime.InteropServices.RuntimeInformation.dll.dll exceeds the OS max path limit. The fully qualified file name must be less than 260 characters.
>   at Microsoft.Build.Shared.FileUtilities.GetFullPath(String path)

**Comment by KirillOsenkov** [comment]
not sure but I think these are benign. I didn’t debug into the workspace to understand it though.

**Comment by jnm2** [comment]
Cool. Would you expect there to be a benefit in me running `msbuild /t:Restore`? I'd rather skip that if it makes no difference.

**Comment by KirillOsenkov** [comment]
Yes there’s more of a chance that it will bring down the dlls so more of the types bind. Otherwise you get broken hyperlinks.

**Comment by KirillOsenkov** [comment]
Hyperlinks from source to source will still work though. Also did you know that you can index a binlog? If you have a build with results and a binlog that’s best, you don’t even need an sln or csproj then.

**Comment by jnm2** [comment]
Is binlog indexing preferable if what I'm doing is cloning/fetching all Git repos at my day job to one place nightly, where I don't want to have to gather and correlate existing CI builds or anything like that? I'd like to do as little as possible. Building and collecting build outputs and binlogs (after cloning/fetching all repos) sounds like a little more work in this situation than just restoring and then pointing HtmlGenerator at the sln files.

**Comment by KirillOsenkov** [comment]
Well, what source.dot.net does is it adds a step to each CI that reads the binlog and generates a self-contained zip archive with sources and binaries, which is published to blob storage. A separate process then pulls all these zip files, and calls HtmlGenerator on them. References are deduplicated by MVID. This way you still capture semantics from each CI, but you don't have to build again separately, you just pull the zips. It's a bit involved and I don't know if the tool that @alexperovich wrote to orchestrate this is available for third-party consumption.

Otherwise just cloning and running HtmlGenerator without building should get you somewhat acceptable results. If you can restore, better. If you can build, even better.

**Comment by jnm2** [comment]
I think I'll build then. I didn't realize the experience could be degraded if a build wasn't run. Do I need the binlog or is simply building the .sln and pointing HtmlGenerator at it enough to get the best experience?

**Comment by KirillOsenkov** [comment]
Building should be enough, but binlog is an absolute guarantee, in case your build is not exactly the same as the real one (say it needs environment variables etc)

**Comment by jnm2** [comment]
Closing because I'm happy to assume there's no degraded functionality as you suspect.
