### ISSUE TITLE
What leads to TFMs being appended to some project names?

### ISSUE THREAD

**Issue by jnm2** [KirillOsenkov/SourceBrowser#161]
![image](https://user-images.githubusercontent.com/8040367/115122506-4232ed80-9f86-11eb-91c5-d2b52e075fe5.png)

**Comment by KirillOsenkov** [comment]
For multitargeting projects only one TFM is chosen randomly for indexing. I suppose we should turn it off?

**Comment by jnm2** [comment]
Oh, that's a simple explanation. Not sure why I thought more of these were multitargeting. I don't mind there being a reminder that I'm missing out on other TFMs so I can keep in mind that after following a reference I might be taken to the wrong TFM.

My preferred target (highest TFM version) is usually listed last in my `<TargetFrameworks>` element. Would you recommend that I start reversing that order, or would it make sense to have HtmlGenerator use the last/highest TFM when it can figure that out instead of being random?

**Comment by KirillOsenkov** [comment]
I think right now it takes the first TFM and I’d think the first TFM is the “primary” one, but I might be wrong. I suppose we could accept a TargetFrameworkPrecedenceList that lists them in order...

**Comment by jnm2** [comment]
This is probably not the only tool that will assume that the first TFM has some special significance. (The only other one I'm aware of is the Windows Forms designer.) I'm okay with reordering all my TFMs.

Tackling indexing all TFMs and taking TFMs into account when tracking references is something I'd be more interested in working on than TargetFrameworkPrecedenceList.

**Comment by KirillOsenkov** [comment]
If you want a future looking source indexing solution, there's a new one slow-cooking over at https://github.com/ref12/codex. But right now it comes with absolutely zero support, zero guarantees, it won't work, is broken, not worth looking into, not ready for adoption, etc. etc.
