### ISSUE TITLE
What is required in order to light up Web Access?

### ISSUE THREAD

**Issue by jnm2** [KirillOsenkov/SourceBrowser#167]
I'm merging public repos on GitHub and repos from an internal deployment of Azure DevOps Server 2020, and I'd like Web Access to show up for both. How is it done for https://source.dot.net and http://sourceroslyn.io?

**Comment by KirillOsenkov** [comment]
I think you can pass serverPath for each solution: https://github.com/KirillOsenkov/SourceBrowser/blob/37624c45a2832b7e6948c7463537177e8719899d/src/HtmlGenerator/Program.cs#L46

**Comment by KirillOsenkov** [comment]
I'm also noticing it's not mentioned in the help:
https://github.com/KirillOsenkov/SourceBrowser/blob/37624c45a2832b7e6948c7463537177e8719899d/src/HtmlGenerator/Program.cs#L278

**Comment by jnm2** [comment]
Okay, I'm going to need it to be something that can be passed to the `/in` file.

> System.ComponentModel.Win32Exception: 'The filename or extension is too long.'

![image](https://user-images.githubusercontent.com/8040367/115153445-ec247f80-a043-11eb-98fe-2b6b6493a834.png)

**Comment by jnm2** [comment]
That can't be right. I forgot to search for .sln files within each repo instead of searching for .sln files in all repos once per repo.

**Comment by KirillOsenkov** [comment]
please make yourself at home

**Comment by jnm2** [comment]
> I think you can pass serverPath for each solution: 

No 'Web Access' link is showing up, but now I'm thinking this is because I'm supposed to pass the server path to each repo root rather than to each solution file.

**Comment by jnm2** [comment]
Got it working mostly, but the argument parsing can't handle there being an `=` character in the URL:

> Invalid Server Path: `C:\Some\Path\SomeRepo=http://someserver/somecollection/someproject/_git/somerepo?version=GCb1b459ab951bdf44e7f9e77f2005620b1e4ab3f6&path=`

**Comment by jnm2** [comment]
@KirillOsenkov What do you think about allowing any number of `=` characters to follow the `=` separator? Or, maybe require both sides to be quoted: `/serverPath:"C:\PathWith=InIt\Abc"="https://abc/def?version=x&path="`

I could also replace `=` with `%3D` but the browser preserves that in the address bar when you navigate there, so it's a very tiny irritation.

**Comment by jnm2** [comment]
Never mind, `%3D` prevents the URL from working. It's got to be `=`.

**Comment by KirillOsenkov** [comment]
anything is fine I guess. We could escape and then unescape after parsing, or use quotes? I think I have a helper somewhere to parse a string ignoring quotes parts (I think it’s in TextUtilities.cs in the MSBuildStructuredLog repo). Sorry on the phone now.

**Comment by jnm2** [comment]
The unescaping thing seems more complicated to get right than the quotes and it also requires the user to do more work than simply slapping quotes around a path and a URL (neither of which should need to permit quote characters).

I think I'll say if there's more than one `=` character, the side/sides meant to contain it/them must be quoted.

**Comment by KirillOsenkov** [comment]
sounds good

**Comment by jnm2** [comment]
@KirillOsenkov What's your feeling on backwards compatibility, preserve it?

```cs
// Allowed forms:
// /serverPath:a=b
// /serverPath:"a=b" (for backwards compatibility)
// /serverPath:"a=1"="b=2"
// /serverPath:"a"="b" (for consistency to make it easy to produce a safe form)
```

**Comment by KirillOsenkov** [comment]
It's up to you, I'd probably write something manually to properly handle all four cases, something along these lines:
https://github.com/KirillOsenkov/MSBuildStructuredLog/blob/fddecd7fcd9c95dc4b65aaa77b50cd95bb668838/src/StructuredLogger/TextUtilities.cs#L142-L188

**Comment by KirillOsenkov** [comment]
or maybe write a regex?

**Comment by jnm2** [comment]
Regex works. Are you comfortable with this code, or can you think of a simpler alternative?

```cs
new Regex(@"\A(?:""(?<from>[^""]*)""=""(?<to>[^""]*)""|""(?<from>[^""=]*)=(?<to>[^""=]*)""|(?<from>[^""=]*)=(?<to>[^""=]*))\Z");
```

**Comment by jnm2** [comment]
Oops, forgot to allow for `"a"=b` and `a="b"`.

**Comment by KirillOsenkov** [comment]
works for me, thanks!
