### ISSUE TITLE
Could 'Web Access' be enabled for .csproj files?

### ISSUE THREAD

**Issue by jnm2** [KirillOsenkov/SourceBrowser#170]
Are there other file types that don't get the 'Web Access' link but could?

**Comment by KirillOsenkov** [comment]
.xml, .ts, .targets, etc.

**Comment by KirillOsenkov** [comment]
This is what generates the Web Access link:
https://github.com/KirillOsenkov/SourceBrowser/blob/45035df10482bf61f6a0ce0ef2d74227d9cb8a0f/src/HtmlGenerator/Pass1-Generation/DocumentGenerator.cs#L298

**Comment by KirillOsenkov** [comment]
I realize with horror that the logic that writes C#, XML and TypeScript is not shared. In my defense, this project was never fully funded, so...

Anyways, this is XML:
https://github.com/KirillOsenkov/SourceBrowser/blob/45035df10482bf61f6a0ce0ef2d74227d9cb8a0f/src/HtmlGenerator/Pass1-Generation/XmlSupport.cs#L51

This is TypeScript:
https://github.com/KirillOsenkov/SourceBrowser/blob/45035df10482bf61f6a0ce0ef2d74227d9cb8a0f/src/HtmlGenerator/Pass1-Generation/TypeScriptSupport.cs#L194

Although TypeScript support is so hopelessly out of date that I doubt anyone relies on it at all.

**Comment by jnm2** [comment]
Interesting, the project filename is EmbedDependencies.csproj but HtmlGenerator thinks the project filename is Techsola.EmbedDependencies.csproj (the root namespace) and thus creates an invalid Web Access URL.

**Comment by jnm2** [comment]
Oops, I was confused by having a topic branch checked out locally, and that's why my URL didn't match.
