### ISSUE TITLE
Some source files are not served even though they exist

### ISSUE THREAD

**Issue by jnm2** [KirillOsenkov/SourceBrowser#171]
I get blackness instead of source if I select this file, and the browser console says it's getting a 404 for `AmbientTasks/obj/Debug/netstandard2.0/.NETStandard,Version=v2.0.AssemblyAttributes.cs.html`.

![image](https://user-images.githubusercontent.com/8040367/115305173-f02fca80-a133-11eb-80d7-28674e54b31a.png)

The file does exist, though, it's just not being served:

![image](https://user-images.githubusercontent.com/8040367/115305558-819f3c80-a134-11eb-9d7b-3dc79c7291f8.png)

**Comment by KirillOsenkov** [comment]
I’m guessing the comma in the filename trips up the JS script

**Comment by jnm2** [comment]
It appears that the JS is constructing a reasonable request, but the server is returning 404.

**Comment by KirillOsenkov** [comment]
Well, one thing I can think of is this:
https://github.com/KirillOsenkov/SourceBrowser/blob/45035df10482bf61f6a0ce0ef2d74227d9cb8a0f/src/SourceIndexServer/wwwroot/scripts.js#L4

It's doing some parsing to support URLs where the hyperlink comes after a comma (all references to a symbol), e.g.
http://sourceroslyn.io/#Microsoft.CodeAnalysis/Compilation/SemanticModel.cs,f8e51661446fa281,references

**Comment by jnm2** [comment]
What's your explanation for why it's sending a GET request for the correct URL which fails with a 404?

`http://localhost:58320/Techsola.EmbedDependencies/obj/Debug/net46/.NETFramework,Version=v4.6.AssemblyAttributes.cs.html`

**Comment by KirillOsenkov** [comment]
I have no explanation :)

You'll have to investigate. Is the file physically there? It's a simple static website.

**Comment by jnm2** [comment]
Yes, it's physically there. I'll dig. I'm just thinking the scripts.js line doesn't look related to the 404.

**Comment by jnm2** [comment]
It's the leading `.` in the filename that prevents the static file provider from making it visible.

**Comment by jnm2** [comment]
Easy, just need to pass the desired ExclusionFilters enum flags to `new PhysicalFileProvider`.

https://github.com/KirillOsenkov/SourceBrowser/blob/45035df10482bf61f6a0ce0ef2d74227d9cb8a0f/src/SourceIndexServer/Startup.cs#L54-L58

**Comment by jnm2** [comment]
Not quite that easy. I passed ExclusionFilters.None and it didn't work, and stepping into ASP.NET Core shows that the PhysicalFileProvider that is handling the request still has ExclusionFilters.Sensitive.

**Comment by jnm2** [comment]
Well, I got it to stop excluding it at https://github.com/dotnet/extensions/blob/v3.1.14/src/FileProviders/Physical/src/PhysicalFileProvider.cs#L253-L257, but it's still giving a 404.

**Comment by jnm2** [comment]
Because I'm dumb and I forgot I renamed the file. 😆
