### ISSUE TITLE
Record types can't be searched or navigated to

### ISSUE THREAD

**Issue by jnm2** [KirillOsenkov/SourceBrowser#181]
They show up in hot pink, don't match searches, aren't clickable when referenced or declared:

![image](https://user-images.githubusercontent.com/8040367/117082183-94f30000-ad0f-11eb-82af-a0803d5721d9.png)

Any tips before I dive in?

**Comment by KirillOsenkov** [comment]
it’s in the Classifier space, ClassifySpans I think (on phone now)

**Comment by KirillOsenkov** [comment]
Here somewhere:
https://github.com/KirillOsenkov/SourceBrowser/blob/ca5e4496700c1922681075559bc3faee325efdac/src/HtmlGenerator/Pass1-Generation/Classifier.cs#L177

**Comment by KirillOsenkov** [comment]
And this is where binding happens:
https://github.com/KirillOsenkov/SourceBrowser/blob/e25ad1eb828093a1e2651c16d038eb0a56584033/src/HtmlGenerator/Pass1-Generation/DocumentGenerator.Links.cs#L58

**Comment by jnm2** [comment]
Cool, testing my guess now. It was indeed `record name`.
