### ISSUE TITLE
Search stopped returning results for System.Console and other .NET APIs

### ISSUE THREAD

**Issue by waf** [KirillOsenkov/SourceBrowser#185]
This is specifically involving the implementation of SourceBrowser on https://source.dot.net. I hope this is the correct repository.

It appears that search results recently degraded; a week or two ago I was able to find results for [`System.Console`](https://source.dot.net/#q=System.Console), [`System.DateTime`](https://source.dot.net/#q=System.DateTime), etc, as well as member searches like [`System.Console.WriteLine`](https://source.dot.net/#q=System.Console.WriteLine). Now, none of those return results.

![image](https://user-images.githubusercontent.com/97195/121838528-41a6a100-cd02-11eb-8441-c77f7c56a160.png)

Here's the HTTP request issued by source.dot.net's front-end code (captured by Firefox's web development tools):

```
GET /api/symbols/?symbol=System.Console HTTP/2
Host: source.dot.net
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:90.0) Gecko/20100101 Firefox/90.0
Accept: text/html
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
DNT: 1
Connection: keep-alive
Referer: https://source.dot.net/results.html
Cookie: ARRAffinity=a4803df7e3ed2a7e2d1721813ab1a3a6cb7c538cb72e82db5880cfd457148c47; ARRAffinitySameSite=a4803df7e3ed2a7e2d1721813ab1a3a6cb7c538cb72e82db5880cfd457148c47
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
Pragma: no-cache
Cache-Control: no-cache
TE: trailers
```

HTTP Response:

```
HTTP/2 200 OK
content-type: text/html; charset=utf-8
content-encoding: gzip
vary: Accept-Encoding
server: Kestrel
request-context: appId=cid-v1:ea35bca4-09f3-4ce2-8530-160bdb9d99ec
x-ua-compatible: IE=edge
x-powered-by: ASP.NET
strict-transport-security: max-age=31536000
date: Mon, 14 Jun 2021 04:06:04 GMT
X-Firefox-Spdy: h2

<div class="note">No results found</div>
<p>Try also searching on:</p>
<ul>
</ul>

```

Further examples are available on the [source.dot.net "overview" page](https://source.dot.net/) -- the first couple of hyperlinks on that page don't show results.

Thanks for creating this great tool—I love it and use it often.

**Comment by KirillOsenkov** [comment]
@alexperovich

**Comment by alexperovich** [comment]
The runtime assemblies are just... not getting indexed at all. The binlog reader isn't finding the compiler invocations somehow.... again...

**Comment by alexperovich** [comment]
https://github.com/dotnet/arcade/pull/7520 should fix things once it gets into runtime.

**Comment by alexperovich** [comment]
This is now fixed.
