### ISSUE TITLE
Can't find results for CoreLib, Collections, LINQ, ...

### ISSUE THREAD

**Issue by JansthcirlU** [KirillOsenkov/SourceBrowser#186]
Classes in some very important namespaces cannot be found when searching, even though the same searches definitely yielded results before (about two weeks ago).

## In the `System.Private.CoreLib` namespace

- [Power (Math)](https://source.dot.net/#System.Private.CoreLib/src/System/Math.CoreCLR.cs,5fb92f1cb8fa90ec,references)
- [Secure String](https://source.dot.net/#System.Private.CoreLib/SecureString.cs,77d68ea938f47705)

## In the `System.Collections.Generic` namespace

- [Linked List](https://source.dot.net/#System.Collections/System/Collections/Generic/LinkedList.cs,df5a6c7b6b60da4f)

## In the `System.Linq` namespace

- [ElementAt](https://source.dot.net/#System.Linq/System/Linq/ElementAt.cs,66b0b5f8174ef9c2)
- [Max](https://source.dot.net/#System.Linq/System/Linq/Max.cs,89e40204a7d64621)
- [OrderBy](https://source.dot.net/#System.Linq/System/Linq/OrderBy.cs,e449fbc07f49dc52)

Among others.

**Comment by KirillOsenkov** [comment]
This has been fixed recently, can you check again please?

**Comment by JansthcirlU** [comment]
Yep, it's fixed! Thanks!
