### ISSUE TITLE
Missing assemblies (source.dot.net)

### ISSUE THREAD

**Issue by hankovich** [KirillOsenkov/SourceBrowser#193]
It looks like the [Microsoft.AspNetCore project](https://github.com/dotnet/aspnetcore/blob/2b0e81f2ff05b6cc9378850d86637ea964e07723/src/DefaultBuilder/src/Microsoft.AspNetCore.csproj) (as well as the whole https://github.com/dotnet/aspnetcore/tree/main/src/DefaultBuilder directory) is not indexed for some reason.

**Comment by KirillOsenkov** [comment]
@alexperovich

**Comment by alexperovich** [comment]
From the logs it appears that the build command the indexer uses (https://github.com/dotnet/source-indexer/blob/main/src/index/repositories.props#L62) doesn't build this directory. This should be fixed by https://github.com/dotnet/aspnetcore/issues/33534

**Comment by hankovich** [comment]
@alexperovich @KirillOsenkov 
Recently started having problems with ([System.Private.CoreLib](https://source.dot.net/#q=System.Private.CoreLib). Looks like it's also missed.

**Comment by hankovich** [comment]
@alexperovich @KirillOsenkov 
Both issues are resolved, thanks!

However, the `Web Access` button seems to be broken.

For example:
On the [AssemblyName](https://source.dot.net/#System.Private.CoreLib/AssemblyName.cs,71a53c064b057975) page it points to [this 404 page](
https://github.com/dotnet/runtime/tree/b9a828220a77e647ef0e6134891651c95912cfa8/src/libraries/System.Private.CoreLib/src/System/Reflection/AssemblyName.cs).

**Comment by alexperovich** [comment]
Its indexing some merge/squash commits that don't show up on github. I will get this fixed.
