### ISSUE TITLE
MSBuild fails on .NET 6 projects during generation

### ISSUE THREAD

**Issue by epetersoni** [KirillOsenkov/SourceBrowser#210]
Even though we are using MSBuild 17.0+ that installs with VS 2022, the MSBuild invoked as part of source browser generation is failing on .NET 6 projects with an error like this:

`Msbuild failed when processing the file 'IsolatedTestRunner\IsolatedTestRunner.NetCore.csproj' with message: C:\Program Files\dotnet\sdk\6.0.101\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.DefaultItems.targets: (134, 5): Targeting .NET 6.0 in Visual Studio 2019 is not supported.`

This means that references to other assemblies by code within the .NET 6 projects do not link correctly in the generated source browser.

I've found that if I remove [this line setting the `VisualStudioVersion` property to `15.0`](https://github.com/KirillOsenkov/SourceBrowser/blob/main/src/HtmlGenerator/Pass1-Generation/SolutionGenerator.cs#L129) these .NET 6 errors stop happening. I'm not sure what else that might affect, so adding a command line argument to specify (or clear) that property would be safer. There also might be a better way to fix this.

Any thoughts on the correct fix?

**Comment by KirillOsenkov** [comment]
Great catch, those lines are no longer required and I removed them. Thanks for investigating this!

**Comment by KirillOsenkov** [comment]
Here you go: 
https://www.nuget.org/packages/SourceBrowser/1.0.39
