### ISSUE TITLE
.Net Frameword referencesource broken

### ISSUE THREAD

**Issue by NetMage** [KirillOsenkov/SourceBrowser#216]
It appears that the .Net Framework site is broken: https://referencesource.microsoft.com/

Clicking on classes results in Resource is missing messages.

Is there a better place to ask for support for the actual Microsoft web sites powered by this project?

**Comment by KirillOsenkov** [comment]
This is a good place. I will follow up.

**Comment by rbhanda** [comment]
This should be working now. Let me know if you are still having issues
