### ISSUE TITLE
Windows specific source files are missing

### ISSUE THREAD

**Issue by cremor** [KirillOsenkov/SourceBrowser#218]
Some, or maybe even all, Windows specific files like [Archiving.Utils.Windows.cs](https://github.com/dotnet/runtime/blob/main/src/libraries/Common/src/System/IO/Archiving.Utils.Windows.cs) or [PathInternal.Windows.cs](https://github.com/dotnet/runtime/blob/main/src/libraries/Common/src/System/IO/PathInternal.Windows.cs) seem to be completely missing on https://source.dot.net

**Comment by alexperovich** [comment]
This is intentional. The product team has asked for the linux sources to be indexed, and source.dot.net can only index one version of the sources at a time.

**Comment by cremor** [comment]
That's very sad to hear. This hugely devalues source.dot.net for me.

**Comment by phizch** [comment]
How hard would it be for MS to have `windows.source.dot.net` and `linux.source.dot.net` etc.? Please ask the product team to do something about this. `source.dot.net` is useless if I can't actually see the source.
