### ISSUE TITLE
Some of ValueTuple<> types are not discoverable [source.dot.net]

### ISSUE THREAD

**Issue by hankovich** [KirillOsenkov/SourceBrowser#222]
Searching for `tuple` (https://source.dot.net/#q=tuple) shows all `Tuple` types from `Tuple`  to `Tuple<T1, T2, T3, T4, T5, T6, T7, TRest>` while searching for `valuetuple` (https://source.dot.net/#q=valuetuple) shows only `ValueTuple`, `ValueTuple<T1>` and `ValueTuple<T1, T2, T3, T4, T5, T6, T7, TRest>`.

`ValueTuple<T1, T2>` seems to be not discoverable at all.
Probably related to #221 

@alexperovich

**Comment by alexperovich** [comment]
It is discoverable, just the name is unexpected due to how roslyn names tuples. https://source.dot.net/#q=%28T1%2C%20T2%29

You have to search for (T1, T2) syntax.

**Comment by hankovich** [comment]
Wow, that's interesting. Thanks!

**Comment by KirillOsenkov** [comment]
I didn't know that either :) TIL!
