### ISSUE TITLE
How to choose a different version of .NET source code for viewing?

### ISSUE THREAD

**Issue by GF-Huang** [KirillOsenkov/SourceBrowser#223]
Default, it show me the latest version: https://source.dot.net/ , but I want to see the older version such like .NET 6, rather than 7 (the latest).

**Comment by svick** [comment]
This is a duplicate of https://github.com/KirillOsenkov/SourceBrowser/issues/207.

**Comment by GF-Huang** [comment]
> This is a duplicate of [](https://github.com/KirillOsenkov/SourceBrowser/issues/207).

Thanks.
