### ISSUE TITLE
Does options handling work well?

### ISSUE THREAD

**Issue by kgh02017** [KirillOsenkov/SourceBrowser#226]
I tried to use SourceBrowser NuGet package version 1.0.42, but I encountered ArgumentException.
I can't solve this problem. Is my usage wrong ?

> HtmlGenerator.exe  /in: 'fullpath-to-solution-file' /out: 'c:/tmp'

????????????: System.ArgumentException: ???????????
   ?? System.IO.Path.NewNormalizePath(String path, Int32 maxPathLength, Boolean expandShortPaths)
   ?? System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   ?? System.IO.Path.GetFullPathInternal(String path)
   ?? Microsoft.SourceBrowser.HtmlGenerator.CommandLineOptions.Parse(String[] args) ?? C:\SourceBrowser\src\HtmlGenerator\CommandLineOptions.cs:? 79
   ?? Microsoft.SourceBrowser.HtmlGenerator.Program.Main(String[] args) ?? C:\SourceBrowser\src\HtmlGenerator\Program.cs:? 20
12:56:34 Exception: System.NotSupportedException: ???????????????????????????
   ?? System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   ?? System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)
   ?? Microsoft.SourceBrowser.HtmlGenerator.CommandLineOptions.AddProject(List`1 projects, String path) ?? C:\SourceBrowser\src\HtmlGenerator\CommandLineOptions.cs:? 267
   ?? Microsoft.SourceBrowser.HtmlGenerator.CommandLineOptions.Parse(String[] args) ?? C:\SourceBrowser\src\HtmlGenerator\CommandLineOptions.cs:? 226

**Comment by KirillOsenkov** [comment]
Have you tried running GenerateTestSite.cmd?

https://github.com/KirillOsenkov/SourceBrowser/blob/main/GenerateTestSite.cmd

**Comment by KirillOsenkov** [comment]
I thinking it should be: `HtmlGenerator.exe C:\foo\bar\baz.sln /out:C:\tmp`

**Comment by kgh02017** [comment]
Thank you for your quick response.

I could finally generate htmls.
Iwas going to try various patterns of options settings, but I'm not familiar with Windows-style option settings, so it seems that "/out:fullpath" (not /out: fullpath) seems to be missing.
