### ISSUE TITLE
BitArray has methods that doesn't exist.

### ISSUE THREAD

**Issue by Donaut** [KirillOsenkov/SourceBrowser#227]
The [BitArray](https://source.dot.net/#System.Collections/System/Collections/BitArray.cs) has methods like "HasAllSet", "HasAnySet" which are doesn't exist. Looking at the MSDN docs these methods are not found both in the framework and the newer core c# versions.

**Comment by svick** [comment]
Those methods indeed don't exist in the most recent released version of .Net (7.0). But the site shows the code from the master branch, i.e. it's effectively a preview of .Net 8 and [those methods exist there](https://learn.microsoft.com/en-us/dotnet/api/system.collections.bitarray.hasallset?view=net-8.0). See also https://github.com/dotnet/runtime/issues/72999 for more details.

To sum up, there is nothing wrong with SourceBrowser.
