### ISSUE TITLE
I am wondering why some files are missing?

### ISSUE THREAD

**Issue by LuohuaRain** [KirillOsenkov/SourceBrowser#229]
https://github.com/dotnet/aspnetcore/tree/3265dc6a9b05c74b199aa39351e5413317df9ad5/src/Components/Authorization/src

https://source.dot.net/#Microsoft.AspNetCore.Components.Authorization/AuthorizeViewCore.cs

![image](https://user-images.githubusercontent.com/37979368/228721732-d4626c38-b45f-40ee-8d15-2ed414007f77.png)

I appreciate your answer.

**Comment by KirillOsenkov** [comment]
.razor files are not supported unfortunately. Only .cs files are supported.

**Comment by LuohuaRain** [comment]
> .razor files are not supported unfortunately. Only .cs files are supported.

Wow, that makes sense. Wish `.razor` would be supported one day! Thank you.
