### ISSUE TITLE
Subdirectory support

### ISSUE THREAD

**Issue by RaphaelHerd** [KirillOsenkov/SourceBrowser#23]
Hey,

first of all I would like to thank you for your nice work. My question or request is more a pull request but I was not able to create them. Is it possible to add subdirectory support? I plan to use your tool on an internal source server. But it's not possible to get a new IP-Address for each generated source view.

I tried it by my own but I think it's easier if you can arrange that because I first have to understand the whole code beforer I can do it by myself.

Thank you very much

Regards
Raphael

**Comment by KirillOsenkov** [comment]
Unfortunately this is really hard with the current architecture and would require large-sweeping changes. I myself won't have time to work on this and I'm unlikely to take a pull request that attempts this (too many things may be broken). However if you're courageous feel free to try it in your own fork.

The biggest problem to solve is the component that's hosted on the webserver (SourceIndexServer). I don't know how to make multiple instances of index co-exist in the same web API (or have multiple API endpoints per host). 

Additionally, we generate URLs of the form /assemblyname/... everywhere, assuming it starts from the root. We'd have to go through the entire codebase and make sure URLs are relative to the root of the current index, not the entire website.

Here's some more information:
https://github.com/KirillOsenkov/SourceBrowser/wiki/Architecture

Instead, one workaround (that admittedly won't work for some scenarios) is to merge all codebases into a single index. Have you tried that?
