### ISSUE TITLE
sourceroslyn.io has invalid certificate

### ISSUE THREAD

**Issue by svick** [KirillOsenkov/SourceBrowser#236]
When I try to visit https://sourceroslyn.io/, I get a NET::ERR_CERT_DATE_INVALID error:

![](https://github.com/KirillOsenkov/SourceBrowser/assets/287848/f136455e-cffc-4df7-b83c-2a4afe8aeedc)

**Comment by KirillOsenkov** [comment]
Fixed, thanks. Not sure why cert renewal isn't automated.
