### ISSUE TITLE
Option to suppress key input when outfile is not empty

### ISSUE THREAD

**Issue by guitarrapc** [KirillOsenkov/SourceBrowser#36]
Description
----

It's much happy if I can pass ```-y``` or any swithc to suppress prompt when I use any CI.

https://github.com/KirillOsenkov/SourceBrowser/blob/cc4b60915b5e71561719dfe7767f8afbe44c9c1b/src/HtmlGenerator/Utilities/Paths.cs#L70

Current workaround
----

clean out folder before HtmlGenerator generate html.

**Comment by KirillOsenkov** [comment]
Yes, we need to implement a flag to suppress that prompt.

**Comment by guitarrapc** [comment]
It also happy if HtmlGenerator could generate only diff files :smile: Currently all generated file detected as totally different and will replace all files in destination.

**Comment by guitarrapc** [comment]
Above comment was misunderstanding. HtmlGenerator perfectly create same hash.

**Comment by KirillOsenkov** [comment]
You can generate into Staging folder, then use https://github.com/KirillOsenkov/ContentSync to copy from Staging to Production.
This way only files which have really changed will be copied.

**Comment by guitarrapc** [comment]
Fantastic. Thank you for advice.

**Comment by KirillOsenkov** [comment]
I've just accepted a PR from @cklutz which implements /force parameter to suppress the confirmation on whether to delete the destination directory. Hope this works as you expect. The change is in 1.0.13 NuGet. I'm going to close this issue but please open a new one if anything is still broken.
