### ISSUE TITLE
Publish to nuget

### ISSUE THREAD

**Issue by giggio** [KirillOsenkov/SourceBrowser#4]
Publish the tool to nuget so we can use it during build to publish our code without the need to add the binary to the repo.

**Comment by luisrudge** [comment]
:+1:

**Comment by caioproiete** [comment]
:+1:

**Comment by seburgi** [comment]
:+1:

**Comment by KirillOsenkov** [comment]
Can you try it out and see if it works for you:
https://www.nuget.org/packages/Microsoft.SourceBrowser

**Comment by KirillOsenkov** [comment]
I'm going to close this one as done, but feel free to let me know if there are any issues.
