### ISSUE TITLE
Project conditional compilation symbols ignored

### ISSUE THREAD

**Issue by jovianarts** [KirillOsenkov/SourceBrowser#48]
I'm noticing that project conditional compilation symbols are being ignored such that declaring "HELLO" as project settings compilation symbols does not enable the code within "#if HELLO". However, code within "#if !HELLO" does get enabled.

I didn't see anything in the documentation stating whether or not this was expected. Is it expected?
Thanks for the help, SourceBrowser is an excellent project!

**Comment by jovianarts** [comment]
I did notice that Class1.cs in Project2.csproj, in the TestSolution does have a "#if _DEBUG" on line 85. That gets disabled since that symbol is not declared, however I didn't see an example of using a defined symbol from the project settings.

Also, I verified that adding #define HELLO within the source itself does work to enable the code within #if HELLO. So only project defined symbols seem affected.

**Comment by KirillOsenkov** [comment]
If you look at this commit: https://github.com/KirillOsenkov/SourceBrowser/commit/b0fdf40be338263d6c891cdbb18e1fae5bc96e8e
you will find that I added the TESTDEFINE conditional compilation directive to the .csproj file. This is what happens when you add it in Project Properties -> Build tab and save the project.

I was then able to run HtmlGenerator and in TestSolution it correctly enabled the TESTDEFINE chunk.

So everything works well, it's probably something on your end. Check that the .csproj file has the <DefineConstants> property in the property group.

**Comment by jovianarts** [comment]
Thanks for the quick reply and the update the test. I've confirmed that this is likely on my end. Part of my projects' configuration is pulled in through an <Import> in the project file, and eventhough the <DefineConstants> in the imported configuration file get used, they appear to conflict while merging with the project specific ones. I've tried different combinations with success looking a little different than I'd hoped, but it will do for now.

If I can ask one more related question:
You add TESTDEFINE under the Debug configuration, and I think SourceBrowser parses the Debug configuration because of the line <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>. However, is there a way to tell SourceBrowser to use a particular configuration when invoking it from the commandline?

For fun I tried modifying msbuildProject (ProjectGenerator.ProjectFile.cs) and its members to dynamically switch the active configuration, but that didn't seem to work, so I'm likely missing something.

**Comment by KirillOsenkov** [comment]
You can pass /p:Configuration=Debug or /p:Configuration=Release = /p:DefineConstants=DEBUG;TRACE;TESTDEFINE to msbuild.exe. 

Here's an extensibility point where you can pass custom properties to MSBuild:
http://sourcebrowser.azurewebsites.net/#HtmlGenerator/Pass1-Generation/SolutionGenerator.cs,90

They will override everything that is in the project file or any of the imported projects. I also recommend checking out:
https://github.com/KirillOsenkov/MSBuildStructuredLog. 

Specifically, you can run msbuild.exe with the /pp switch like this:
https://github.com/KirillOsenkov/MSBuildStructuredLog/wiki/MSBuild%20Tips%20&%20Tricks#msbuildexe-pp
This will flatten the entire tree of imported projects, so you can read that "mega" project and see in which order the DefineConstants property is set.

**Comment by KirillOsenkov** [comment]
Oh, and when I added TESTDEFINE to the test project, it only landed in a conditional property group by accident. If you want it to be valid for all project configurations, place it in a PropertyGroup that doesn't have any conditions. Preferably at the end of your project so that it overrides assignments to DefineConstants that are made in any of the imported projects. The MSBuild evaluation model is "flatten all imports first, then evaluate top-down, last assignment wins".

**Comment by jovianarts** [comment]
Thanks again for all your help, it's been instrumental. I used the MSBuildStructuredLog as you recommended. Strangely enough, I did find an inconsistency between what MSBuildStructuredLog returned about what msbuildProject gets assigned. Following your advice regarding the order of evaluation where the last entry wins, I understood that AllPropertiesEvaluated was the ordered list where duplicates existed and Properties was the list with duplicated removed where the last duplicate wins. When I looked through the order in the AllPropertiesEvaluated list, I realized my issue.

That was likely enough for you, but in case you are interested in the inconsistency I discovered, I was able reproduce it by modifying your test solution in the following way:

Created a Pre.targets file in the TestCode folder:
`
<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="4.0">  
  <PropertyGroup>
    <IsDebug>$(Configuration.EndsWith('Debug'))</IsDebug>
  
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
     <DefineConstants>DEBUG;TRACE</DefineConstants>
  </PropertyGroup>
</Project>
`

Created a Common.targets file in the TestCode folder:
`
<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="4.0">
  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <DefineConstants>$(DefineConstants);IMPORTEDTESTDEFINE;</DefineConstants>
  </PropertyGroup>
</Project>
`

Modified the Project2.csproj:
`
  ...
  <Import Project="..\Pre.targets" />     <-- added this line after your first Import tag.
  ...
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>      <-- removed this line since it's now in the Pre.targets file.
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>      <-- removed this line since it's now in the Pre.targets file.
  ...  
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">      <-- replaced this line with <PropertyGroup Condition=" $(IsDebug) ">
  ...
  <Import Project="..\Common.targets" />      <-- added this line above the last Import tag.
`

Added the following to Class1.cs:
`
#if IMPORTEDTESTDEFINE
public class ThisShouldBeEnabledViaImportedTarget { }
#endif
`

The result:

* When using MSBuildStructuredLog, Project2.csproj's DefineConstants all show DEBUG;TRACE;TESTDEFINE;IMPORTEDTESTDEFINE;
* When probing msbuildProject, Properties's DefineConstants shows DEBUG;TRACE;IMPORTEDTESTDEFINE;

I realize the first reaction should be "why are you doing that?" and it's the right reaction, but it still highlights a strange behavior, I think.

My solution was to move the definition of IsDebug to below the assignment of the default configuration in the Pre.targets file and this worked for SourceBrowser.

Thanks again for all your help! And if my explanation was too complicated and you'd like me to include the files, I'd be happy to.
