### ISSUE TITLE
What to deploy?

### ISSUE THREAD

**Issue by FransBouma** [KirillOsenkov/SourceBrowser#5]
It's likely me, but I have a hard time figuring out what to deploy. I've generated the index output using HtmlGenerator and created a webapp on IIS on our local server to test what to do on the remote server. When browsing to this webapp I see the familiar interface and things work when browsing. However search throws a missing method exception, which is likely due to the fact I do something wrong. So I see the SourceIndexServer, but to get that started according to the docs, I have to alter a line in a .vs config file. But what do I do in my own webserver? I have no deep knowledge of IIS configs other than setting up an app, application pool etc. So I'm a bit lost what to deploy (the Index folder generated by HtmlGenerator **and** SourceIndexBrowser, or just Htmlgenerator?). 

TIA and sorry if this is documented already somewhere and I overlooked it.

**Comment by cklutz** [comment]
For me it just worked by using the "content" of the directory I specified using the "/out:" option of the HtmlGenerator. Albeit I tested it on the same machine where I compiled the tool and ran HtmlGenerator.exe.

**Comment by seburgi** [comment]
Yepp and if you don't use an output path it will generate the site in "bin\Debug\HtmlGenerator\Index" by default. Then for testing purposes start IIS Express from command line as follows:

"c:\Program Files (x86)\IIS Express\iisexpress.exe" /path:.\bin\Debug\HtmlGenerator\Index\

**Comment by FransBouma** [comment]
Yeah that works for me, but search fails (gives error. If I start SourceIndexBrowser from vs.net and the config file edit, it does work). Does search fail for you too in that scenario?

**Comment by cklutz** [comment]
OK, I should add that I tried it using the "full" IIS. I just might a website out ouf the "/out" directory. Everything works so far (except my [other issue](https://github.com/KirillOsenkov/SourceBrowser/issues/6), but that is not related).

**Comment by FransBouma** [comment]
Ok, thanks. I'll double check what's wrong with my IIS setup (win2012r2) and retry.

**Comment by FransBouma** [comment]
I keep getting this exception:
```
System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'. at Microsoft.SourceBrowser.SourceIndexServer.Models.ResultsHtmlGenerator.AppendAffiliateLinks(Query query) at Microsoft.SourceBrowser.SourceIndexServer.Models.ResultsHtmlGenerator.Generate(Stopwatch sw, Index index, String usageStats) at Microsoft.SourceBrowser.SourceIndexServer.Controllers.SymbolsController.GetHtmlCore(String symbol, String usageStats) at Microsoft.SourceBrowser.SourceIndexServer.Controllers.SymbolsController.GetHtml(String symbol)
```

and ... I suddenly remembered something: if .NET 4.6 is available on your system when you compile (it is), Roslyn will make assumptions how to optimize empty arrays and the resulting code will thus contain references to System.Array.Empty<T>. See https://github.com/dotnet/roslyn/issues/1103

My server doesn't have .NET 4.6 installed, so this pops up. This isn't an issue with SourceBrowser, but a run-in with a Roslyn/.NET 4.6 side effect. I'll close the issue, as there's little Kirill or others can do.

**Comment by FransBouma** [comment]
I've compiled SourceIndexBrowser against .NET 4.5 now, copied the dlls into the bin folder of the index output and which runs as a webapp on the server, and it still gives this same error. Apparently the compilation of the SourceIndexBrowser still uses .NET 4.6 assemblies and optimizes the array.empty usage, causing problems on systems with .NET 4.5 installed but not .NET 4.6. 

@KirillOsenkov, any idea what to do to make the output at least work on .NET 4.5? TIA

**Comment by cklutz** [comment]
@FransBouma Good to know. I was hoping to take the 4.6 build along with me to use it on one of our 4.5-only boxes at work. A "casual" build on a 4.5-only machine, that I attempted on friday, failed.

**Comment by KirillOsenkov** [comment]
Unfortunately I remember I ran into a whole bunch of limitations when making it work on 4.5 and I ultimately gave up. I think because the Roslyn binaries I use were compiled against 4.6 and so they expect the .NET Framework to contain Array.Empty.

I'm afraid 4.6 is a hard requirement and unless you or anyone else want to go to great lengths trying to recompile Roslyn without 4.6 (and I can't even imagine how difficult that must be) we'll have to require 4.6.

**Comment by KirillOsenkov** [comment]
On the other hand, you only need to target Common and SourceIndexServer to 4.5 and they don't depend on Roslyn. You can try and see if you run into more issues when converting them.

**Comment by FransBouma** [comment]
I set SourceIndexServer to .net 4.5 and I still got the issue. I forgot to set Common to .net 4.5 too (as the issue occurs in the SourceIndexServer dll). Will try that later today, see if that helps :)

**Comment by KirillOsenkov** [comment]
Remember that if you're compiling on a machine with 4.6 MSBuild will pass 4.6 references due to the bug Nick and you found.

-----Original Message-----

**Comment by FransBouma** [comment]
Yes I thought about that, but I hard-set the .NET version in the SourceIndexServer project to .net 4.5, so it should then pass .net 4.5 to the compiler, or is there some 'optimization' in the compilation process which makes msbuild mess that up? :)

I'll try tomorrow (no time today) or wednesday to see if I compile it separately in a separate solution, it will work on .net 4.5

**Comment by KirillOsenkov** [comment]
When you build, pay attention to the command line (what references are passed to csc.exe?). Just type MSBuild SourceIndexServer.csproj and carefully read the csc.exe invocation command line. mscorlib reference is likely to be 4.6.

**Comment by KirillOsenkov** [comment]
Frans, I've set Common and SourceIndexServer to target .NET 4.5. Try it out whenever you have time and let me know if there's anything I can do to help.

**Comment by FransBouma** [comment]
I hoped to have time today but didn't. I hope to try it tomorrow (thursday)! I'll report back with my findings :)

**Comment by FransBouma** [comment]
Using .NET 4.5 as target in both Common and SourceIndexServer still gives the issue: 

> System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'. at Microsoft.SourceBrowser.SourceIndexServer.Models.ResultsHtmlGenerator.AppendAffiliateLinks(Query query) at Microsoft.SourceBrowser.SourceIndexServer.Models.ResultsHtmlGenerator.Generate(Stopwatch sw, Index index, String usageStats) in C:\Myprojects\VS.NET Projects\GitHub\SourceBrowser\src\SourceIndexServer\Models\ResultsHtmlGenerator.cs:line 25 at Microsoft.SourceBrowser.SourceIndexServer.Controllers.SymbolsController.GetHtmlCore(String symbol, String usageStats) in C:\Myprojects\VS.NET Projects\GitHub\SourceBrowser\src\SourceIndexServer\Controllers\SymbolsController.cs:line 78 at Microsoft.SourceBrowser.SourceIndexServer.Controllers.SymbolsController.GetHtml(String symbol) in C:\Myprojects\VS.NET Projects\GitHub\SourceBrowser\src\SourceIndexServer\Controllers\SymbolsController.cs:line 26

Looking into what msbuild is doing.

**Comment by FransBouma** [comment]
Oh this is odd. I have the SourceIndexServer project properties tab open in vs.net 2015. I change target framework to .NET 4.5, it pops up the dialog with the warning blabla, I click OK, it has a hard time repainting the tab but it doesn't close it and ... it keeps it at .net 4.6!

I'll alter the csproj xml to set it hardcoded to .net 4.5, see how that turns out.

**Comment by FransBouma** [comment]
SourceIndexServer's csproj xml says: <TargetFrameworkVersion>v4.5</TargetFrameworkVersion>, but opening the project properties tab for SourceIndexServer, it says target framework is .NET 4.6! Tossing away the .vs folder with the .suo files has no effect either, reopening the sln in vs.net neither.

Same thing with Common, I can't set the target framework there to .NET 4.5. It's 4.5 in the xml of the csproj files, it's not in vs.net itself, and I recon that's because of a reason which e.g. msbuild will use as well, but why this is, is unclear. Do you see the same thing? (project properties in vs.net)

I created a new solution file (copied the old one, just kept common and sourceindexserver) and loaded that, same thing: I can't set the target framework to 4.5 in the project properties (if I change the value, it does something, marks itself as altered but still shows 4.6, file on disk shows 4.5).

When I run msbuild <mysmallsolution> on the commandline, I see it does pick .net 4.6 BCL libraries when building the two projects Common and SourceIndexServer. Which is totally stupid as it's targeting .NET 4.5, not .NET 4.6. There's no mention of .NET 4.6 anywhere. 

When I build my own code, do I now have to worry it's targeting .NET 4.6 as well even though I target .NET 4.5? I checked on the command line and the solution of mine which does have a .NET 4.5 target project seems to build against .NET 4.5, so there's some relief, but there is a massive bug in Microsoft's tooling somewhere and it can't be shoved aside as some edge case.

**Comment by KirillOsenkov** [comment]
Did you pull latest from master? I change the target to 4.5.

You need to hand edit the .csproj and set the target framework AFTER including Common.proj.

-----Original Message-----

**Comment by FransBouma** [comment]
I didn't pull latest from master, I worked with the pull I had. The csproj files are referring to 4.5, that's the problem, on disk everything is OK! Even in the solution with just Common and SourceIndexServer. There's nowhere something saying it targets 4.6, both csproj files are set to 4.5!

I'll pull from master again and see if that changes things, but I don't see how, as the files I had should have worked, as I simply changed the framework version inside the IDE. It bugged there.

**Comment by KirillOsenkov** [comment]
Read Common.props very carefully :) In MSBuild, the order of evaluation is important. Your change of target framework, if it was before Import Project Common.props, had no effect. I set target framework 4.6 globally in Common.props.

Just pull latest from master and work with that.

-----Original Message-----

**Comment by FransBouma** [comment]
Ah, now I see Common.props. Still I think vs.net should have given me a message that changing the FW target is of no use if you change it in the UI and this kind of setup is used. 

Building the code from the latest src and copying the 2 dlls from sourceindexserver to the web app's bin folder makes search work!

So having these two projects on .net 4.5 works out fine in this case :)

Solved.

**Comment by KirillOsenkov** [comment]
Cool. Glad to hear. VS project properties should be aware of imported projects, and it isn't, no question there. There's hope to improve it next release.

-----Original Message-----

**Comment by FransBouma** [comment]
Running fine now :) http://referencesource42.llblgen.com

Made some changes to the CSS so it's easier on the eye on non-Retina/4K displays ;)

**Comment by KirillOsenkov** [comment]
Looks awesome!

-----Original Message-----
