### ISSUE TITLE
C# 7 out var declarations are not supported

### ISSUE THREAD

**Issue by SLaks** [KirillOsenkov/SourceBrowser#52]
http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/UseObjectInitializer/ObjectCreationExpressionAnalyzer.cs,94

The `var` keyword should be linked to its type, and the declared variable should be recognized as a variable.

**Comment by alexperovich** [comment]
This happens because the source indexer is built against the old version of roslyn that doesn't have support for out var. Building it against the new version should fix this.

**Comment by SLaks** [comment]
@KirillOsenkov, can you rebuild the Roslyn index against the latest Roslyn build?

**Comment by KirillOsenkov** [comment]
I hope to get to it soonish.

**Comment by KirillOsenkov** [comment]
So I've hacked the internal fork that generates http://source.roslyn.io to update to Roslyn 2.0.0-rc. This uncovered a bunch of issues with Roslyn NuGet packages, so I'll wait for them to fix them first before updating this repo.

For now you can try http://source.roslyn.io and see if it looks OK now.

**Comment by KirillOsenkov** [comment]
I've ran into a whole host of issues (basically 2.0.0-rc package of Roslyn is not usable without jumping through hoops), so this will have to wait until Roslyn 2.0 RTM is out.

**Comment by SLaks** [comment]
What's wrong the the Roslyn RC package?

**Comment by KirillOsenkov** [comment]
It's non-trivial to get the MSBuildWorkspace working. Kevin says there are problems with finding the MSBuild 15 toolset. Additionally you need to install a few other packages manually (ManagedEsent, Elfie, RuntimeInformation). Also there's a crash in compiler (it doesn't tolerate mscorlib missing). Basically just a 1000 papercuts.

**Comment by KirillOsenkov** [comment]
This should be now fixed.
