### ISSUE TITLE
InternalsVisibleTo

### ISSUE THREAD

**Issue by jovianarts** [KirillOsenkov/SourceBrowser#53]
Any plans to support InternalsVisibleTo?

ps. Happy new year!

**Comment by KirillOsenkov** [comment]
What do you mean? I thought it's supported? What is not working?

**Comment by jovianarts** [comment]
Sorry to waste your time, it does work. My issue was actually related to the symbol issue I had a few months back and forgot to make a fix to this other solution I was using. My fault. And thanks for the quick response as always!

**Comment by KirillOsenkov** [comment]
Any time :)
