### ISSUE TITLE
"SolutionExplorer" view contents with multiple solutions

### ISSUE THREAD

**Issue by cklutz** [KirillOsenkov/SourceBrowser#6]
(sorry for the mess if you follow this via E-Mail; but I figured it would be better to rephrase and update the original question)

Hi,

first of all, thanks for putting this out in the wild :-)

I have a source tree that looks structurally like this:

    \<toplevel>
         solution1.sln
         solution2.sln
         solution3.sln
    \<toplevel>\solution1-projects\src\<project1>
    \<toplevel>\solution1-projects\src\<project2>
    \<toplevel>\solution2-projects\src\<project3>
    \<toplevel>\solution2-projects\src\<project4>
    \<toplevel>\solution3-projects\src\<project5>
    \<toplevel>\solution3-projects\src\<project6>

Each solution depends on the previous. That is, <project3> and <project4> depend on the assemblies build by solution1.sln, etc.

Now, when I invoke the HtmlGenerator.exe tool like so, `HtmlGenerator.exe /out:<somedir> Solution1.sln Solution2.sln Solution3.sln` I get indexed sources for _all_ projects, but a "SolutionExplorer" that only reflects the _last solution file specified on the command line_.

Furthermore, the files between the different solutions are not cross-referenced. For example, a type from a project in solution1, that appears in a project in solution2, is no link to that source file.

I can understand if you don't have the time to debug into this (I will try that myself over the next week or so), but maybe you have an idea what could be going wrong here.

Thanks,
Christian

**Comment by cklutz** [comment]
OK, I'd like to add some more information on my particalur setup and current results.

I have a source tree that looks structurally like this:

    \<toplevel>
         solution1.sln
         solution2.sln
         solution3.sln
    \<toplevel>\solution1-projects\src\<project1>
    \<toplevel>\solution1-projects\src\<project2>
    \<toplevel>\solution2-projects\src\<project3>
    \<toplevel>\solution2-projects\src\<project4>
    \<toplevel>\solution3-projects\src\<project5>
    \<toplevel>\solution3-projects\src\<project6>

Each solution depends on the previous. That is, <project3> and <project4> depend on the assemblies build by solution1.sln, etc.

Now, when I invoke the HtmlGenerator.exe tool like so, `HtmlGenerator.exe /out:<somedir> Solution1.sln Solution2.sln Solution3.sln` I get indexed sources for _all_ projects, but a "SolutionExplorer" that only reflects the _last solution file specified on the command line_.

Furthermore, the files between the different solutions are not cross-referenced. For example, a type from a project in solution1, that appears in a project in solution2, is no link to that source file.

I can understand if you don't have the time to debug into this (I will try that myself over the next week or so), but maybe you have an idea what could be going wrong here.

Thanks again,
Christian

**Comment by KirillOsenkov** [comment]
The fact that only one solution explorer (the last one) is generated is by current design. There is no logic to merge solution explorers although now that I think about it I don't see why it couldn't work. I'll see if I can improve this.

The fact that files from different solutions are not cross-referenced is a surprised to me, this shouldn't happen. They should transparently merge as if they all were in a single solution. If you have a very simple repro steps (with two simple solutions?) I'd appreciate it.

**Comment by KirillOsenkov** [comment]
Could you file a separate bug about files from different solutions not being cross-referenced? Let's make this bug about the solution explorer only.

**Comment by KirillOsenkov** [comment]
I've made a change that merges multiple solutions into a single solution explorer at the end. Could you try it out? Thanks!

**Comment by cklutz** [comment]
I'll do both (create a new bug and test what you have changed), when I get back to my .net 4.6 equipped PC). At work we're still frozen to 4.5.

**Comment by KirillOsenkov** [comment]
I've checked in a fix, I hope it works :) Can you try it out and let me know? Thanks!

**Comment by cklutz** [comment]
Hi, sorry for the late response, but I couldn't make it any sooner :-(
Just wanted to let you know, that the latest version indeed resolves the above issues - both of them FWIW. Even the "solution cross-referencing" works as expected. Thanks. :-)

**Comment by KirillOsenkov** [comment]
Awesome!
