### ISSUE TITLE
can't build

### ISSUE THREAD

**Issue by XtremePlayzCODE** [KirillOsenkov/SourceBrowser#62]
Everytime I try to build the project, there is always 6 errors no matter what and it is bugging me so bad

**Comment by KirillOsenkov** [comment]
could you pkease paste the errors here?

**Comment by XtremePlayzCODE** [comment]
Sorry for the extremely late response, but I tried to build Microsoft's Reference Source to try and get https://referencesource.microsoft.com offline, but errors keep popping up. Will attach an error log in a minute.

**Comment by XtremePlayzCODE** [comment]
[log.txt](https://github.com/KirillOsenkov/SourceBrowser/files/801333/log.txt)
 Here's the log when I try to build SourceBrowser

**Comment by KirillOsenkov** [comment]
You're building using MSBuild 4.0. Only MSBuild 14.0 is supported, you can get it with Visual Studio 2015. Do you have VS 2015 installed? Which VS version are you using? Open Developer Command prompt and build from there.

Before you build you'll need to restore NuGet packages.

**Comment by XtremePlayzCODE** [comment]
I have VS 2015 installed and I will attempt this again, thank you!

**Comment by KirillOsenkov** [comment]
Please reopen if you still have problems. Thanks.
