### ISSUE TITLE
I added support to Visual studio 2017 and Nuget 4.0 and new .net solutions

### ISSUE THREAD

**Issue by guylando** [KirillOsenkov/SourceBrowser#63]
You can find it here: https://github.com/guylando/SourceBrowser are welcome to test\merge it

**Comment by BilelYahia** [comment]
Please create a pull request so people can comment to the changes.

**Comment by KirillOsenkov** [comment]
Once we have VS 2017 RTM I can go through the changes and merge myself. I don't want to do this before RTM though.

**Comment by KirillOsenkov** [comment]
I've gone through and made SourceBrowser use MSBuild 15 and Roslyn 2.0.0. I don't want to convert most .csproj files to the new format for now (I did convert the easy ones). Thanks for your help.
