### ISSUE TITLE
Path issues

### ISSUE THREAD

**Issue by XtremePlayzCODE** [KirillOsenkov/SourceBrowser#76]
###### (i know i've been opening a lot of issues, sorry)

When hosting a generated SourceBrowser site on a path instead of main-domain/subdomain, many URLs are broken and redirect to the site root

**Comment by KirillOsenkov** [comment]
Yes this is known and hard to fix. Unfortunately SourceBrowser right now can only be hosted at the root of a domain or subdomain.

Closing as a duplicate of https://github.com/KirillOsenkov/SourceBrowser/issues/23
