### ISSUE TITLE
Comment formatting lapses in invalid XML in documentation comments

### ISSUE THREAD

**Issue by JesperTreetop** [KirillOsenkov/SourceBrowser#79]
See line 69 and line 76 in [ImageAnimator.cs](http://referencesource.microsoft.com/#System.Drawing/commonui/System/Drawing/ImageAnimator.cs,5c62a859bbe32b7d). (The text turns black after a comma.)

**Comment by KirillOsenkov** [comment]
Good eye, thanks for spotting this! We'll take a look.

**Comment by JesperTreetop** [comment]
[This looks like](https://referencesource.microsoft.com/#mscorlib/system/int32.cs,257) either the exact same thing or something closely related (things that confuse or error out an XML parser in a (mistaken?) doc comment). If Roslyn hasn't been updated yet, it might be another error case.

**Comment by KirillOsenkov** [comment]
Yes, reference source runs on a much older snapshot of source browser, we'll likely never fix it there (for various reasons).
