### ISSUE TITLE
Latest Roslyn version changed Glyph numbers

### ISSUE THREAD

**Issue by tamasvajk** [KirillOsenkov/SourceBrowser#81]
Running the generator with Roslyn 2.3.1 results in unrecognized symbol types in the generated index. For example interfaces are not searchable and show up as "symbols". Most probably the Glyph IDs changed in Roslyn, and `IndexEntry.GetKind` returns the default symbol kind text for them.

**Comment by KirillOsenkov** [comment]
Thanks, fixed.
