### ISSUE TITLE
Could not generate the web site from 1.0.15 binaries

### ISSUE THREAD

**Issue by bouchraScript** [KirillOsenkov/SourceBrowser#85]
Hello,
I need to generated the web site for two source code  repositories. For that i passed to the HtmlGenerator.exe two .sln files, i tried with the 1.0.14 version, the web site is generated but in the repo explorer bar i can see only one repository, i have to navigate through assmeblies to get to the second one.

So i wanted to try the latest version 1.0.15, but the web site isn't generated (i don't see any index.html ) , it fails with the exception bellow.

Is there a change between binaries of the two versions ? because i cannot find all .css/.js/.html files that used to be located in "\tools\web".

I have VS 2015 installed, i have both MSBuild 12 and 14. I am on Windows 7.

Thank you

````
15:57:11: First chance exception
System.Runtime.InteropServices.COMException (0x80040154): Retrieving the COM class factory for component with CLSID {177F0C4A-1CD3-4DE7-A32C-71DBBB9FA36D} failed due to the following error: 80040154 Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG)).
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
```

```
15:57:11: First chance exception
System.DllNotFoundException: Unable to load DLL 'Microsoft.VisualStudio.Setup.Configuration.Native.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Microsoft.Build.Shared.VisualStudioLocationHelper.GetSetupConfiguration(ISetupConfiguration& configuration, IntPtr reserved)
   at Microsoft.Build.Shared.VisualStudioLocationHelper.GetQuery()
```

```
15:57:12: First chance exception
System.ArgumentNullException: Value cannot be null.
Parameter name: o
   at System.Runtime.InteropServices.Marshal.GetIUnknownForObjectNative(Object o, Boolean onlyInContext)
   at Microsoft.Build.Tasks.InteropUtilities.RCWForCurrentContext`1..ctor(T rcw)
```

```
15:57:12 Workspace failed: Msbuild failed when processing the file 'D:\repo1\repo1.csproj' with message: C:\Program Files (x86)\MSBuild\12.0\bin\amd64\Microsoft.CSharp.CurrentVersion.targets: (448, 9): Invalid command line switch for "Csc.exe". Value cannot be null.
Parameter name: o
15:57:12 Msbuild failed when processing the file 'D:\repo1\repo1.csproj' with message: C:\Program Files (x86)\MSBuild\12.0\bin\amd64\Microsoft.CSharp.CurrentVersion.targets: (448, 9): Invalid command line switch for "Csc.exe". Value cannot be null.
```

**Comment by KirillOsenkov** [comment]
Yes unfortunately I think you need VS 2017 and MSBuild 15.

**Comment by bouchraScript** [comment]
Thank you for your reply.
Is it possible with 1.0.14 to generate one web site from multiple .sln ?

**Comment by KirillOsenkov** [comment]
I think it was possible, I'm not sure though. Try using the command-line help.

Also just try specifying multiple solutions on the command line.

**Comment by bouchraScript** [comment]
Yes the help shows that it is possible. As i mentioned, i already tried with two repos and the web site is generated, my issue is that i can't see both repositories on the index of the web site.
I tried to add in a file my two .sln full paths and passe it to HtmlGenerator through "/in", but didn't work either.
I will try to install MSBuild 15 and test with the latest version. I will keep you in touch

**Comment by bouchraScript** [comment]
With MSBuild 15 and 1.0.15 version of sourcebrowser i no longer get the exception mentioned above, but still the index.html is not generated.
The destination folder of my web site has the following content : 

- index (which doesn't contain the index.html)

- refs

- runtimes



And a bunch of Microsoft dlls

**Comment by bouchraScript** [comment]
Can you please provide me an explanation on the issue described in my last comment ? we do really hope to migrate to the latest version.
Thank you in advance

**Comment by KirillOsenkov** [comment]
Could you read through https://github.com/KirillOsenkov/SourceBrowser/issues/80 and see if the investigation we did there helps?

**Comment by bouchraScript** [comment]
Thank you for replay, i am using binaries from Nuget and the solution provided by the linked issue work when working with sources.
I suppose the latest nuget binaries version takes into account Alex's PR. If this isn't the case, i will try installing VS 2017 and work with sources instead, i will keep you informed.

**Comment by KirillOsenkov** [comment]
I see, maybe I should regenerate and upload the latest NuGet binaries.

**Comment by bouchraScript** [comment]
That would be great. Thank you

**Comment by KirillOsenkov** [comment]
I've uploaded this: https://www.nuget.org/packages/Microsoft.SourceBrowser/1.0.16

Could you please try and let me know if this works for you? Thanks!

**Comment by bouchraScript** [comment]
I did test with the new binaries on my machine which has MSBuild 15, i get to see the wwwroot folder generated which has the index.html, content folder...etc.
In my IIS server i link the web site with the index folder, but i don't get to see anything . 
As @yaakov-h did in the linked issue, when i copy the content of wwwroot to index it works fine. We are generating the web site on every push on the repository so it won't be practical to copy wwwroot content each time.
No Errors.txt nor Messages.txt is generated.

**Comment by KirillOsenkov** [comment]
Here's how I work with this:
1. `git clone https://github.com/KirillOsenkov/SourceBrowser`
2. Open SourceBrowser.sln in Visual Studio 2017
3. F5

By default it will generate the TestSolution.sln to `C:\SourceBrowser\src\SourceIndexServer\index`. After that, you can set the SourceIndexServer project as startup and F5. It will open IIS Express and the website should work fine.

Here's the layout on disk:
![image](https://user-images.githubusercontent.com/679326/32853389-009669c0-c9f0-11e7-96fc-26f8073ba8a5.png)

```
Index
    index
        Errors.txt
        DeclaredSymbols.txt
        results.html
        SolutionExplorer.html
        ...
    wwwroot
        index.html
        overview.html
        scripts.js
        styles.css
        ....
        content
            icons
                ...
```

When you serve the website, point it at the root Index, not at the index\index.

**Comment by bouchraScript** [comment]
Hello @KirillOsenkov , sorry for the late replay.
Infortunatlly i was unable to test with the sources on my machine. For that i still keep investigating in the issue.
Here is what i find in the system log after enbaling the "stdoutLogEnabled" in the web.config:

`Failed to start process with commandline '"dotnet" .\Microsoft.SourceBrowser.SourceIndexServer.dll', ErrorCode = '0x80004005'.`

The folder ./logs isn't created, i see this warning : 

`Warning: Could not create stdoutLogFile \\?\D:\MySite\logs\stdout_1588_20171120111616.log, ErrorCode = -2147024891.`

My machine has .net core 1.0.1, could this be the source of the problem? because i see in the _Microsoft.SourceBrowser.SourceIndexServer.runtimeconfig.json_ file this:
 
```
"framework": {
      "name": "Microsoft.NETCore.App",
      "version": "1.1.2"
    },
```

**Comment by KirillOsenkov** [comment]
Yes, try installing .Net Core SDK 1.1 and also 2.0. We've just updated from 1.1 to 2.0 but I didn't publish 2.0 packages yet.

**Comment by bouchraScript** [comment]
Hello, sorry for the delay.
I used .Net core SDK 1.1.5 and i get to visualize the web site perfectly.
So to sum up for future visitors who use binaries instead of sources, here is what i did:

- for the proxy exceptions i mentioned first in the issue: i added this to HtmlGenerator.config
```
         <system.net>
             <defaultProxy useDefaultCredentials="true" />
         </system.net>

```
By this the web site generation should normally work fine
- you need .net core sdk >=1.1.* in order to visualize the web site on IIS server
- point your IIS web site to the root folder of your sourcebrowser, let's say Index in this hierarchy:
```
Index
    index
        Errors.txt
        DeclaredSymbols.txt
        results.html
        SolutionExplorer.html
        ...
    wwwroot
        index.html
        overview.html
        scripts.js
        styles.css
        ....
        content
            icons
                ...
```
- if you encounter any other problems with the server, say 502/401 server errors, it is actually a problem with your IIS web site configuration not with the sourcebrowser generator.

Thank you @KirillOsenkov for all your clarifications. The issue can be closed now

**Comment by KirillOsenkov** [comment]
👍
