### ISSUE TITLE
when will support for asp.net core 2.0 source code

### ISSUE THREAD

**Issue by WeihanLi** [KirillOsenkov/SourceBrowser#86]
It would be better if will support for asp.net core 2.0 source code

**Comment by KirillOsenkov** [comment]
Is it not supported now? What are you seeing that is not working as expected?

**Comment by WeihanLi** [comment]
What I see now on <https://aspnetsource.azurewebsites.net/> is Asp.Net Core 1.0

**Comment by KirillOsenkov** [comment]
Oh, you'd like that website to be updated to index 2.0 source? @natemcmaster

**Comment by KirillOsenkov** [comment]
Consider opening an issue there: https://github.com/natemcmaster/AspNetSourceBrowser

**Comment by WeihanLi** [comment]
Yeah,thanks
