### ISSUE TITLE
Need to update the Microsoft.Build.* packages

### ISSUE THREAD

**Issue by oxfordemma** [KirillOsenkov/SourceBrowser#91]
If you have updated to VS 15.5, then you can no longer run the generator.
Updating all of the Microsoft.Build.* packages to 15.5.180 fixes the issue.

https://github.com/Microsoft/msbuild/issues/2775

**Comment by KirillOsenkov** [comment]
I've fixed the issue, but uploading the new NuGet package for Microsoft.SourceBrowser will take a bit longer.
