### ISSUE TITLE
Trouble publishing the website with 2.1.300-preview2-008324

### ISSUE THREAD

**Issue by KirillOsenkov** [KirillOsenkov/SourceBrowser#93]
1. git clone https://github.com/KirillOsenkov/SourceBrowser
2. Install dotnet 2.1.300-preview2-008324
3. Try to restore and build

```
"C:\SourceBrowser\src\HtmlGenerator\HtmlGenerator.csproj" (default target) (1)
->
"C:\SourceBrowser\src\SourceIndexServer\SourceIndexServer.csproj" (Publish targ
et) (5) ->
(_RunForCore target) ->
  EXEC(1,11): error CS0246: The type or namespace name 'System' could not be fo
und (are you missing a using directive or an assembly reference?) [C:\SourceBro
wser\src\SourceIndexServer\SourceIndexServer.csproj]
  EXEC(1,54): error CS0518: Predefined type 'System.String' is not defined or i
mported [C:\SourceBrowser\src\SourceIndexServer\SourceIndexServer.csproj]
  C:\Users\kirillo\.nuget\packages\microsoft.aspnetcore.mvc.razor.viewcompilati
on\2.0.2\build\netstandard2.0\Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.ta
rgets(60,5): error MSB3073: The command ""dotnet" exec --runtimeconfig "C:\Sour
ceBrowser\src\SourceIndexServer\bin\Release\netcoreapp2.0\Microsoft.SourceBrows
er.SourceIndexServer.runtimeconfig.json" --depsfile "C:\SourceBrowser\src\Sourc
eIndexServer\bin\Release\netcoreapp2.0\Microsoft.SourceBrowser.SourceIndexServe
r.deps.json" "C:\Users\kirillo\.nuget\packages\microsoft.aspnetcore.mvc.razor.v
iewcompilation\2.0.2\build\netstandard2.0\Microsoft.AspNetCore.Mvc.Razor.ViewCo
mpilation.dll" @"obj\Release\netcoreapp2.0\microsoft.aspnetcore.mvc.razor.viewc
ompilation.rsp"" exited with code 1. [C:\SourceBrowser\src\SourceIndexServer\So
urceIndexServer.csproj]
```

@alexperovich @natemcmaster hey guys, I'm a complete noob when it comes to .NET SDK, could one of you help me understand what's going on and who to ask for help?

Usually when HtmlGenerator.csproj builds, it is supposed to deploy the website (SourceIndexServer) binaries to the same location next to the website output. This is not happening because the Web folder in HtmlGenerator output directory is empty (it only contains AffiliateLinks.txt).

I'd be super grateful if you could help me figure this out! Much appreciated.

**Comment by KirillOsenkov** [comment]
Hmm, I've just noticed that if I open SourceBrowser.sln in the IDE and right-click on SourceIndexServer and select Publish, then I get the same error in the IDE as well.

**Comment by natemcmaster** [comment]
You've probably hit https://github.com/aspnet/MvcPrecompilation/issues/162. Try this
```xml
<PropertyGroup>
    <MvcRazorCompileOnPublish>false</MvcRazorCompileOnPublish>
    <PreserveCompilationContext>false</PreserveCompilationContext>
</PropertyGroup>
```

**Comment by KirillOsenkov** [comment]
Yup, that's exactly it, the workaround works like a charm.

Thank you so much!
:heart:

**Comment by natemcmaster** [comment]
Happy to help :)

**Comment by fbarletta** [comment]
@KirillOsenkov 

I had the same issue just now and deleted the original bin folder to have a clean publish. This fixed it for me without having the change Razor to `false`
