### ISSUE TITLE
Hyperlink not working

### ISSUE THREAD

**Issue by KirillOsenkov** [KirillOsenkov/SourceBrowser#95]
http://source.monodevelop.com/#Microsoft.VisualStudio.Composition/RuntimeExportProviderFactory.cs,417c6d94e9ce8fb1

http://source.monodevelop.com/Microsoft.VisualStudio.Composition/P/c312efdf30365d66.html

**Comment by KirillOsenkov** [comment]
Is it because of the `+`?
http://source.monodevelop.com/#Microsoft.VisualStudio.Composition/RuntimeExportProviderFactory.cs,c312efdf30365d66

**Comment by andre-ss6** [comment]
Another thing I noted is that some sites, like Azure Devops, encodes the comma (which [seems to be correct behavior](https://stackoverflow.com/questions/8828702/why-is-the-comma-url-encoded)). The URL for source.dot.net does not work when the comma is URL encoded: https://source.dot.net/#System.Private.CoreLib/CancellationTokenSource.cs%2c1008 (notice the `%2c`; If you replace it for a comma, then it works).

**Comment by KirillOsenkov** [comment]
since http://source.monodevelop.com is defunct now, I have no idea what those URLs were and what the problem was. Since we have a new bug for the comma, I'm closing this issue.
